# Flutter'ın dosyayı bulabilmesi için gerekli olan üst satır
post_install_path = File.join(File.dirname(File.expand_path(__FILE__)), '..', '..', '..', '..', 'flutter', 'packages', 'flutter_tools', 'bin', 'xcode_backend.sh')

# Bu satırı ekleyerek Flutter kütüphanelerini tanıtıyoruz
require File.expand_path(File.join(File.dirname(__FILE__), '..', '.flutter-plugins-dependencies'))

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Bu komutun çalışması için Flutter ayarlarının yüklü olması gerekir
  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end